Add new test_maps, which tests all reachable levels for referential integrity.
It starts in (hardcoded) `studyroom` and goes through all doors.
Checks performed (explicitly):
- door points to a valid door in a valid level
  Exception: doors can point to no door in other level, as in that case default position is used (position of door `main`); found in:
  - level _womens-bathroom_, door _secret_
  - level _valley_, unnamed door at [149,0]
  - level _black-caverns-2_, unnamed door at [133,7]
  - level _black-caverns-2_, door _seabluff_
  There are couple of doors pointing to _overworld_ (in _new-abedtown_), so there is some special treatment of it.
- door's property `button` has to be recognized by _inputcontroller_ (currently one of `UP`, `DOWN`, `LEFT`, `RIGHT`, `SELECT`, `START`, `JUMP`, `ATTACK`, `INTERACT`)
- door's property `sound` has to be `false`/`true` or name of valid sound
- door's property `key` has to be loadable key, can't test if the key is also placed somewhere in the world, because some keys are loaded dynamically (e.g. white_crystal)
- level's property `music` has to be name of valid music

Loading a level checks references to other things implicitly, e.g. tilesets images.

Level's field `map` is currently not needed for testing, so it's being set to `nil`, lowering memory consumption.

All levels are loaded first, then the checks are performed, so checking of doors doesn't cause multiple loads of the same level(s).
Also, this enables separating different tests (i.e. doors from music and possible future tests).

Another option would be to load a level, perform all possible checks immediately (except doors check), store information needed for doors check and load next level in the queue.
This should lower memory consumption even more, at the expense of new data structures.

Sounds and musics are being tested in batches - they are collected first and tested afterwards.
This improves error message in case of an error - all sources referring to failed sound/music are reported.